# Generated by Django 2.2.6 on 2019-11-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=150)),
                ('bug_report', models.TextField()),
                ('bug_severity', models.CharField(max_length=1)),
                ('bug_published', models.DateTimeField(verbose_name='date reported')),
            ],
        ),
    ]
