# Generated by Django 2.2.6 on 2019-11-10 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=200)),
                ('type_summary', models.CharField(max_length=200)),
                ('type_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Project Types',
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date reported'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_summary', models.CharField(max_length=200)),
                ('project_slug', models.CharField(default=1, max_length=200)),
                ('project_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ProjectType', verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Project', verbose_name='Project'),
        ),
    ]
